### ISSUE TITLE
Pins are private

### ISSUE THREAD

**Issue by abdouhl** [sns-sdks/python-pinterest#4]
When i create pin the pin appear for me  but not for other users

**Comment by abdouhl** [comment]
This when I see from my account
![this from my profile](https://user-images.githubusercontent.com/73205653/163869260-d57a47bd-d201-4885-8abd-bd1db0f0e732.jpg)

**Comment by abdouhl** [comment]
This when i see my profile from others users accounts

![Screenshot_2022-04-18-20-54-41-59.jpg](https://user-images.githubusercontent.com/73205653/163869365-64cf8b6e-f9c1-4da9-a8e5-6c0beea143b7.jpg)

**Comment by MerleLiuKun** [comment]
Sorry for late reply,

Have you point the board or pin's privacy?
